### ISSUE TITLE
Unix compatibility

### ISSUE THREAD

**Issue by fernandoandreotti** [hooman650/BioSigKit#1]
Hi, while attempting to import an ECG on an RunBioSigKit instance I was confronted with the following error

> Error using load
> Unable to read file '<whole_path>/SampleSignals/\ECG1.mat'. No such file or directory.

I believe this is caused by the backslash on function ImportSig. To provide compatibility you should do something like `slashchar = char('/'*isunix + '\'*(~isunix));`

and use slashchar instead.

**Comment by hooman650** [comment]
Thank you for pointing this out. I just fixed it.
