### ISSUE TITLE
Add contributing/community guidelines

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [hooman650/BioSigKit#4]
Can you please work on community guidelines? I suggest adding a `CODE_OF_CONDUCT.md` and a `CONTRIBUTING.md` file and I suggest linking to them in you `README.md`. 

See the links below to learn more about the why/how of setting up these files. 

See also the code of conduct and contributing files for my personal project:
https://github.com/gibbonCode/GIBBON

More information: 

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

https://opensource.guide/

https://www.contributor-covenant.org/

**Comment by hooman650** [comment]
Thank you! I have adapted the contributor-covenant and linked it to the readme.md.

Cheers
