### ISSUE TITLE
Community Guidelines: Seeking Support

### ISSUE THREAD

**Issue by bzenger** [hooman650/BioSigKit#5]
It looks like there is no specific information about seeking support for software usage. Do you have a plan in place to help community members with possible technical problems outside of the context of bug reporting?

**Comment by hooman650** [comment]
Hi @bzenger , sure. I am not sure what would be the best way? I was thinking to approach it as questions in the issue section...but could you please be kind enough to share your experience or suggestion? I have been thinking to add a technical wiki to the project that describes in much more details the background about each subroutine 

Thanks in advance 
Hooman

**Comment by bzenger** [comment]
Hi @hooman650 we use email list serves for specific software packages. i.e. each package has an email list you can send that links to developers and expert users alike. A wiki is another, reasonable option. I also think using the "issues" as a community forum is not a bad solution, it should just be stated in the documentation as such. Does that make sense? We find that communicating with our end users is one of the most important aspects of creating good opensource projects.

**Comment by hooman650** [comment]
Great idea! I am working on a wiki but that would take a bit more time to be completed, if it is okay I am going to follow your suggestion of  having it as "issues" and add it to the documentation as a section for expert users... Thank you for the suggestion..cheers

**Comment by Kevin-Mattheus-Moerman** [comment]
@hooman650 I think mentioning questions/queries should be posted as issues in the documentation is sufficient.

**Comment by bzenger** [comment]
@hooman650 Great! Let me know when that is updated in the documentation and I will finish the review.

**Comment by hooman650** [comment]
@bzenger and @kevin-Mattheus-Moerman thanks. This has been added as a section in the readme.md of the toolbox.

**Comment by hooman650** [comment]
Thank you!
