### ISSUE TITLE
Minor paper edits

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [hooman650/BioSigKit#6]
Here are some minor suggested edits for the JOSS paper: 

1. I recommend adding comma's as proposed in this sentence:
> For the ECG processing, BioSigKit offers several popular algorthims that, with the exception of (Pan & Tompkins, 1985), are only available in C language. 

2. Consider using hyphens in `easy-to-use`

3. Section 1.6 mentions `ecg` twice, please use capital letters i.e. `ECG` as is used elsewhere.

**Comment by hooman650** [comment]
Thank you! This is done!
